Adding pre-commit hooks support for black and flake8(PEP8 compliance …
winny-/sillypaste pull request #12
Opened 2021-10-03 18:43 UTC by BodaleDenis

- I've added pre-commit hooks support for the project
- I've included black and flake8 for compliance check with PEP8
I hope it is OK, it would be nice to test on your side too

P.S: All hooks have passed directly, so that is a good job 😄

2021-10-03 20:18 UTC, BodaleDenis commented
pip install pre-commit
pre-commit install

This should be enough, in order to have pre-commit up and running locally

2021-10-07 01:04 UTC, winny- requested changes
Thank you for the pull request!  I have a suggested a tormatting change and wanted your opinion on the `requirements.txt` change?  Maybe that change could be omitted?  What do you think?

2021-10-07 01:04 UTC, winny- commented on requirements.txt
> +flake8
Let's omit these two additions from `requirements.txt`.  If one installs pre-commit (via their OS's package manager or `pip install --user`), that should be sufficient.  If I'm not mistaken, `pre-commit` automatically pulls in tools needed to run the checks, so we shouldn't need `flake8` in that case.

2021-10-07 01:04 UTC, winny- commented on .pre-commit-config.yaml
> +    - id: flake8
I am a little opinionated about formatting YAMLs.  What do you think?
```suggestion
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
```

2021-10-07 19:27 UTC, BodaleDenis commented
Ok I will do the changes

2021-10-08 16:55 UTC, winny- commented
Will do.  One outstanding discussion item here https://github.com/winny-/sillypaste/pull/12#discussion_r723775724

2021-10-12 13:36 UTC, BodaleDenis commented
flake and pre-commit are now removed from requirements.txt

2021-10-12 15:33 UTC, winny- reviewed
One final change requested, then I'll go ahead and merge

2021-10-12 15:33 UTC, winny- commented on requirements.txt
> +
This should remove the blank line.

```suggestion
```

2021-10-13 19:34 UTC, merged

2021-10-13 19:36 UTC, winny- commented
I went ahead and committed that code review suggestion to delete a line.  I'm still learning how to use the code review feature, so hoping I'm doing this right!

Thank you for the pull request :-) !  If you want to make further changes feel free to open an issue first to talk about it, and open a PR.  I'll help ensure the changes have a good chance of being merged in.